### PR TITLE
POL-219 Adjust spacing for primary toolbar

### PR DESCRIPTION
**Pull request by josejulio**
Updated the Wizard

# Wizard

## Before
Screenshot_2020-05-15_11-28-02
Screenshot_2020-05-15_11-27-49

## After

Screenshot_2020-05-15_11-13-47
Screenshot_2020-05-15_11-13-19

# Main page

## Before

Screenshot_2020-05-15_11-27-32
Screenshot_2020-05-15_11-27-22

## After

Screenshot_2020-05-15_11-24-22
Screenshot_2020-05-15_11-24-11

### CODE REVIEW

**Comment by josejulio** [comment]
@katierik Could you take a look?

**Comment by katierik** [comment]
Can we hold on this until the upcoming PF breaking change release? 
The information I have is that spacing is being tightened up across the board by 4-8px and I don't have a comprehensive list of what is changing. Its possible that this alignment issue is solved there.

FYI - https://medium.com/patternfly/patternflys-major-release-everything-you-need-to-know-1f9e50be81e8

**Comment by josejulio** [comment]
> Can we hold on this until the upcoming PF breaking change release?

Yes

**Comment by theute** [comment]
@katierik  are we still waiting on something ?

**Comment by katierik** [comment]
The frontend components toolbar has some spacing issues (Jiras open, would need to dig up). 
The desired spacing is to have 16px between each item. 
Pagination on top is compact, with full pagination in the footer of the table.

**Pull request closed without merging**
