### PR TITLE
Preparations to push to an explicit branch

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by theute** [comment]
Should we comment out the first part with master and prod branches (until we release to prod-stable) ?
 I see a risk that we merge v2 in "ci-beta" (for instance) and other branches being on v1, but then if we push v3 on master (accidentally ?), all the ci|qa prod|stable will be on v3

**Comment by josejulio** [comment]
> Should we comment out the first part with master and prod branches (until we release to prod-stable) ?
> I see a risk that we merge v2 in "ci-beta" (for instance) and other branches being on v1, but then if we push v3 on master (accidentally ?), all the ci|qa prod|stable will be on v3

That's a good point, I'll comment them out to avoid any mistake there.

**Comment by josejulio** [comment]
I commented the "master" path only, the "prod" is harder to happen. Leaving it there and in case we might need to push something to prod.

If you feel safer commenting that out, let me know.

**Comment by theute** [comment]
Sounds good to me. I leave it up to you to merge whenever it makes sense for you to "split" those branches

**Pull request merged**
