### PR TITLE
POL-114 First version of typeahead

### PR DESCRIPTION
**Pull request by josejulio**
Currently only showing the facts keys on the typeahead

Peek 2020-04-01 12-39

### CODE REVIEW

**Comment by theute** [comment]
That looks awesome, I'm eager to give this a try.
I see a DNM and need to resolve conflict.
(I didn't do a code review)

**Comment by josejulio** [comment]
I set the DNM because I though this was not yet needed, I'll rebase later today so someone can review and merge if is good enough.

**Comment by josejulio** [comment]
Rebased, anyone wants to take a look?

**Comment by theute** [comment]
I had a quick look already, nothing scary. I will merge and can check the feature in CI before we push to prod again.

**Pull request merged**
