### PR TITLE
POL-226 Adds last triggered

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by pilhuhn** [comment]
I think it looks good. I am just removing the lastEvaluated code from UI-backend.

**Comment by josejulio** [comment]
> I think it looks good. I am just removing the lastEvaluated code from UI-backend.

ok, will update the ui too.

**Comment by josejulio** [comment]
Friendly reminder to future me: if https://github.com/RedHatInsights/policies-ui-frontend/pull/92 is merged, we need to update the Csv keys to remove lastEvaluated and add lastTriggered

**Comment by josejulio** [comment]
Rebase, pending to generate the types off the openapi.json when the lastTriggered PR is merged.

**Comment by spinder** [comment]
Merging. The ui updates look good.  I ran with latest ui-backend and re-ran: `yarn generate-schema` and `yarn schema:generate`.

**Pull request merged**
